# Generated by Django 5.2 on 2025-09-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookswap',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('CANCELLED', 'Cancelled'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='PROPOSED', max_length=9),
        ),
        migrations.AlterField(
            model_name='bookswapevent',
            name='type',
            field=models.CharField(choices=[('PROPOSE', 'Proposed'), ('CANCEL', 'Cancelled'), ('ACCEPT', 'Accepted'), ('DECLINE', 'Declined'), ('COMPLETE', 'Completed')], max_length=8),
        ),
    ]
