# Generated by Django 5.2 on 2025-10-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklisting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('SWAPPED', 'Swapped'), ('REMOVED', 'Removed')], default='PENDING', max_length=9),
        ),
    ]
