# Generated by Django 5.2 on 2025-10-18 19:49

from django.db import migrations


def populate_common_genres(apps, schema_editor):
    Genre = apps.get_model('core', 'Genre')
    
    common_genres = [
        # top-level genres
        "Fiction",
        "Non-Fiction",
        "Young Adult",
        "Children",
        # fiction sub-genres
        "Romance",
        "Sci-Fi",
        "Fantasy",
        "Thrillers",
        "Mystery & Suspense",
        "Manga",
        "Literary Fiction",
        "Historical Fiction",
        "Horror",
        "Graphic Novels",
        "Poetry",
        # non-fiction sub-genres
        "Biography & Memoir",
        "Business",
        "Cookbooks",
        "Colouring Books",
        "Faith & Spirituality",
        "Health",
        "History & Politics",
        "Music, Movies & Performing Arts",
        "Parenting & Family Relationships",
        "Science & Nature",
        "Self-Help & Wellness",
    ]
    
    for genre_name in common_genres:
        Genre.objects.get_or_create(name=genre_name)


def reverse_populate_common_genres(apps, schema_editor):
    Genre = apps.get_model('core', 'Genre')
    
    common_genres = [
        # top-level genres
        "Fiction",
        "Non-Fiction",
        "Young Adult",
        "Children",
        # fiction sub-genres
        "Romance",
        "Sci-Fi",
        "Fantasy",
        "Thrillers",
        "Mystery & Suspense",
        "Manga",
        "Literary Fiction",
        "Historical Fiction",
        "Horror",
        "Graphic Novels",
        "Poetry",
        # non-fiction sub-genres
        "Biography & Memoir",
        "Business",
        "Cookbooks",
        "Colouring Books",
        "Faith & Spirituality",
        "Health",
        "History & Politics",
        "Music, Movies & Performing Arts",
        "Parenting & Family Relationships",
        "Science & Nature",
        "Self-Help & Wellness",
    ]
    
    Genre.objects.filter(name__in=common_genres).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_common_genres, reverse_populate_common_genres),
    ]
