# Generated by Django 5.2 on 2025-04-30 02:17

import isbn_field.fields
import isbn_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklisting',
            name='isbn',
            field=isbn_field.fields.ISBNField(blank=True, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
    ]
