# Generated by Django 5.2 on 2025-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bookswap_status_alter_bookswapevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklisting',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SWAPPED', 'Swapped'), ('REMOVED', 'Removed')], default='AVAILABLE', max_length=9),
        ),
    ]
