# Generated by Django 5.2 on 2025-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booklisting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookswap',
            name='offered_books',
        ),
        migrations.RemoveField(
            model_name='bookswap',
            name='requested_books',
        ),
        migrations.AddField(
            model_name='bookswap',
            name='offered_listings',
            field=models.ManyToManyField(related_name='offered_listings', to='core.booklisting'),
        ),
        migrations.AddField(
            model_name='bookswap',
            name='requested_listings',
            field=models.ManyToManyField(related_name='requested_listings', to='core.booklisting'),
        ),
    ]
