# Generated by Django 5.2 on 2025-09-30 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booklisting_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookswap',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('CANCELLED', 'Cancelled'), ('RESCINDED', 'Rescinded'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='PROPOSED', max_length=9),
        ),
        migrations.AlterField(
            model_name='bookswapevent',
            name='type',
            field=models.CharField(choices=[('PROPOSE', 'Proposed'), ('CANCEL', 'Cancelled'), ('RESCIND', 'Rescinded'), ('ACCEPT', 'Accepted'), ('DECLINE', 'Declined'), ('COMPLETE', 'Completed')], max_length=8),
        ),
        migrations.AlterField(
            model_name='bookswapevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
