# Generated by Django 5.2 on 2025-05-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_bookswap"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookswap",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=9,
            ),
        ),
    ]
