# Generated by Django 5.2 on 2025-05-07 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_bookswap_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookswap",
            name="status",
        ),
        migrations.CreateModel(
            name="BookSwapDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("CANCELLED", "Cancelled"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                        ],
                        max_length=9,
                    ),
                ),
                ("decision_made_on", models.DateTimeField(auto_now_add=True)),
                (
                    "swap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bookswap"
                    ),
                ),
            ],
        ),
    ]
