# Generated by Django 5.2 on 2025-05-11 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_decision_bookswapdecision_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookSwapDecision",
        ),
    ]
