# Generated by Django 5.2 on 2025-05-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_delete_bookswapdecision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookswap",
            old_name="proposed_on",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="bookswap",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Proposed"),
                    ("CANCELLED", "Cancelled"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="bookswap",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
