# Generated by Django 5.2 on 2025-05-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_bookswapevent_bookswapmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookswapevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("CANCEL", "Cancel"),
                    ("ACCEPT", "Accept"),
                    ("DECLINE", "Decline"),
                ],
                max_length=7,
            ),
        ),
    ]
