# Generated by Django 5.2 on 2025-05-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_bookswapevent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookswapevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("CANCEL", "Cancelled"),
                    ("ACCEPT", "Accepted"),
                    ("DECLINE", "Declined"),
                ],
                max_length=7,
            ),
        ),
    ]
