# Generated by Django 5.2 on 2025-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bookswap_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookswapevent',
            name='type',
            field=models.CharField(choices=[('PROPOSE', 'Proposed'), ('CANCEL', 'Cancelled'), ('ACCEPT', 'Accepted'), ('DECLINE', 'Declined')], max_length=7),
        ),
    ]
