# Generated by Django 5.2 on 2025-05-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_bookswapevent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booklisting",
            name="author",
            field=models.CharField(default="Testing", max_length=255),
            preserve_default=False,
        ),
    ]
